# Use a imagem base Debian Bullseye
FROM debian:bullseye

# Crie o diretório para os arquivos estáticos
RUN mkdir -p /var/www/html/static

# Copie os arquivos estáticos para o diretório
COPY static /var/www/html/static
